### ISSUE TITLE
/usr/lib/python3.8/site-packages/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol: jbig2_page_out

### ISSUE THREAD

**Issue by Ripo-za** [BasioMeusPuga/Lector#141]
It appear this error when  i run 

Traceback (most recent call last):
  File "/usr/bin/lector", line 33, in <module>
    sys.exit(load_entry_point('lector==0.5.1', 'gui_scripts', 'lector')())
  File "/usr/bin/lector", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/lector/__main__.py", line 42, in <module>
    from lector import sorter
  File "/usr/lib/python3.8/site-packages/lector/sorter.py", line 58, in <module>
    from lector.parsers.pdf import ParsePDF
  File "/usr/lib/python3.8/site-packages/lector/parsers/pdf.py", line 20, in <module>
    import fitz
  File "/usr/lib/python3.8/site-packages/fitz/__init__.py", line 3, in <module>
    from fitz.fitz import *
  File "/usr/lib/python3.8/site-packages/fitz/fitz.py", line 18, in <module>
    from . import _fitz
ImportError: /usr/lib/python3.8/site-packages/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol: jbig2_page_out

**Comment by je-vv** [comment]
Isn't this rather a PyMuPDF bug?  Or perhaps a missing rebuild of libmupdf?  See, on Arch (python is python3 on Arch), when building PyMuPDF 1.18.4, and trying the build before installing:
```
  local python_version=$(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
  PYTHONPATH="$PWD/build/lib.linux-$CARCH-${python_version}" python -c 'import sys; sys.path.remove(""); import fitz'
```

> ==> Starting check()...
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/vasqueja/.cache/aurutils/sync/python-pymupdf/src/PyMuPDF-1.18.4/build/lib.linux-x86_64-3.8/fitz/__init__.py", line 3, in <module>
>     from fitz.fitz import *
>   File "/home/vasqueja/.cache/aurutils/sync/python-pymupdf/src/PyMuPDF-1.18.4/build/lib.linux-x86_64-3.8/fitz/fitz.py", line 18, in <module>
>     from . import _fitz
> ImportError: /home/vasqueja/.cache/aurutils/sync/python-pymupdf/src/PyMuPDF-1.18.4/build/lib.linux-x86_64-3.8/fitz/_fitz.cpython-38-x86_64-linux-gnu.so: undefined symbol: jbig2_page_out
