### ISSUE TITLE
Pyqt5 error

### ISSUE THREAD

**Issue by DukeValentine** [BasioMeusPuga/Lector#15]
I installed the application from the aur into my desktop. When I launch it gives me this error:
`pkg_resources.DistributionNotFound:The 'PyQt5>=5.10.1' distribution was not found and is required by lector`
However, I have this package installed already:
`sudo pacman -Ss pyqt5`
`extra/pyqt5-common 5.10.1-1 [installed]`
    `Common PyQt files shared between python-pyqt5 and python2-pyqt5`
`extra/python-pyqt5 5.10.1-1 [installed]`
`    A set of Python 3.x bindings for the Qt5 toolkit`

**Comment by BasioMeusPuga** [comment]
I've removed version checks from the setup.py altogether. I really don't like how unreliable it's being. See if that fixed it?

**Comment by DukeValentine** [comment]
It's giving another error now:
Traceback (most recent call last):
  File "/usr/bin/lector", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5' distribution was not found and is required by lector

**Comment by trinaldi** [comment]
@DukeValentine  I'm using Arch Linux, FWIW. A simple 'pip3 install pyqt5' did the trick.

**Comment by amitbha** [comment]
Same problem.
The system installation of python-pyqt5 is not found by lector.

**Comment by BasioMeusPuga** [comment]
I'm almost certain this isn't *my* bug based on the fact that I can find references to exactly this at other places.

In any case, I've decided on the nuke it from orbit option until a workaround can be found. The setup.py no longer checks for the PyQt installation.

**Comment by amitbha** [comment]
Manjaro Linux with package python-pyqt5  5.10.1-1 installed.
Lector installed from aur.

# lector 
Traceback (most recent call last):
  File "/usr/bin/lector", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5' distribution was not found and is required by lector

**Comment by BasioMeusPuga** [comment]
@amitbha 
This is a compile from the latest master? Because like I said, the setup.py doesn't even check for PyQt5 anymore. If it were an issue with Lector proper, we'd be getting an ImportError.

Also, try `pip install pyqt5`

**Comment by amitbha** [comment]
The [aur version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lector-git) having problem is:
pkgver=r198.50089cb-1
After `yaourt -S lector-git`, it works well. 😌
Yet no .desktop file, only start it from terminal.

**Comment by DukeValentine** [comment]
Weirdly enough, trying to install once again worked. It launches without any errors now.
