### ISSUE TITLE
crash: toFillPolygon() not enough arguments

### ISSUE THREAD

**Issue by tofuhead** [BasioMeusPuga/Lector#18]
trying to launch it I get a crash.

python 3.6.3
pyqt 5.7

I haven't used QPainterPath() so not an expert, but looking at the code on that line:
mask = QtGui.QRegion(self.path.toFillPolygon().toPolygon()) 

toFillPolygon indeed doesn't have any arguments passed to it? 

here's the error:

Traceback (most recent call last):
  File "lector/__main__.py", line 1206, in <module>
    main()
  File "lector/__main__.py", line 1199, in main
    form = MainUI()
  File "lector/__main__.py", line 87, in __init__
    self.metadataDialog = MetadataUI(self)
  File "/home/basse/src/Lector/lector/metadatadialog.py", line 42, in __init__
    mask = QtGui.QRegion(self.path.toFillPolygon().toPolygon())
TypeError: toFillPolygon(self, QTransform): not enough arguments

**Comment by tofuhead** [comment]
edit. sorry, JUST after putting this up I realized my qt and pyqt5 versions are not what the requirements seem to say on the page :) sorry again.
