### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by erik-sk** [BasioMeusPuga/Lector#30]
From either build and install or running  __main__.py, getting this error. Pretty sure all dependencies are met. Do I need to set a path to my ebooks before opening the app?

Locale: en_US (No translations found)
Database returned no paths for settings...
Available parsers: *.pdf *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
Database returned nothing
Traceback (most recent call last):
  File "/usr/local/bin/lector", line 11, in <module>
    load_entry_point('lector==0.2.1', 'gui_scripts', 'lector')()
  File "/usr/local/lib/python3.6/dist-packages/lector-0.2.1-py3.6.egg/lector/__main__.py", line 1256, in main
    form = MainUI()
  File "/usr/local/lib/python3.6/dist-packages/lector-0.2.1-py3.6.egg/lector/__main__.py", line 222, in __init__
    self.lib_ref.generate_library_tags()
  File "/usr/local/lib/python3.6/dist-packages/lector-0.2.1-py3.6.egg/lector/library.py", line 260, in generate_library_tags
    i[0]: (None, None) for i in db_library_directories}
TypeError: 'NoneType' object is not iterable

**Comment by BasioMeusPuga** [comment]
This has been fixed. However, you're not at the latest commit. 

I assume you followed the instructions in the README to install. Just update your clone/download and repeat the process.

**Comment by erik-sk** [comment]
It works now. Thanks.
