### ISSUE TITLE
Error launching Lector on Arch

### ISSUE THREAD

**Issue by andyperisho** [BasioMeusPuga/Lector#32]
I have installed lector on arch via `trizen -S lector-git`
The install was successful, but after running `lector` in term, I get this error.
Any idea what's wrong?
```
Traceback (most recent call last):
  File "/usr/bin/lector", line 11, in <module>
    load_entry_point('lector==0.3.2', 'gui_scripts', 'lector')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/lector/__main__.py", line 45, in <module>
    from lector.definitionsdialog import DefinitionsUI
  File "/usr/lib/python3.6/site-packages/lector/definitionsdialog.py", line 22, in <module>
    from PyQt5 import QtWidgets, QtCore, QtGui, QtMultimedia
ImportError: libQt5Multimedia.so.5: cannot open shared object file: No such file or directory
```

**Comment by andyperisho** [comment]
Installing manually solves the problem. Did you update the aur `PKGBUILD`?
