### ISSUE TITLE
installation on trueOS

### ISSUE THREAD

**Issue by mich2018** [BasioMeusPuga/Lector#34]
Hi i have this error when i launch the Lector.
I am using TrueOS 18.04 stable 

Traceback (most recent call last):
  File "/usr/local/bin/lector", line 11, in <module>
    load_entry_point('lector==0.3.3', 'gui_scripts', 'lector')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/lector/__main__.py", line 386
    f'{ebooks_string} ({self.available_parsers})')
                                                ^
SyntaxError: invalid syntax

**Comment by BasioMeusPuga** [comment]
You need to run this with Python **3.6**. Any version of Python before that will not work.
If your distro still defaults to python 2.7, repeat the install instructions with
`python3 setup,py build` and `python3 setup.py install`
