### ISSUE TITLE
Trying to run, get the following.

### ISSUE THREAD

**Issue by tatpap** [BasioMeusPuga/Lector#7]
`Traceback (most recent call last):
  File "./__main__.py", line 24, in <module>
    import sorter
  File "/home/tim/zaapps/Lector-dev/sorter.py", line 49, in <module>
    from parsers.epub import ParseEPUB
  File "/home/tim/zaapps/Lector-dev/parsers/epub.py", line 22, in <module>
    from ePub.read_epub import EPUB
  File "/home/tim/zaapps/Lector-dev/ePub/read_epub.py", line 24, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
`

**Comment by BasioMeusPuga** [comment]
This looks like a dependency issue. Are you sure you have BeautifulSoup
installed (properly)?

**Comment by tatpap** [comment]
That was it, got it...thanks.
On a side note, many, many tech ebooks come as PDF and it looks like they can't be imported..that somthing in the works?

**Comment by BasioMeusPuga** [comment]
Yes, it is. But YSK implementing *proper* pdf support is a non trivial thing. It will take time.
