### ISSUE TITLE
Add Epub Book Error

### ISSUE THREAD

**Issue by vendforce** [BasioMeusPuga/Lector#8]
Database returned no paths for settings...
Available parsers: *.epub *.mobi *.azw *.azw3 *.azw4 *.prc *.cbz *.cbr
Database returned nothing
Exception in thread Thread-1:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/user/Lector-dev/sorter.py", line 165, in read_book
    book_ref.read_book()
  File "/user/Lector-dev/parsers/epub.py", line 37, in read_book
    contents_found = self.book_ref.read_epub()
  File "/user/Lector-dev/ePub/read_epub.py", line 43, in read_epub
    self.generate_book_metadata(contents_path)
  File "/user/Lector-dev/ePub/read_epub.py", line 129, in generate_book_metadata
    self.book['year'] = int(self.book['year'][:4])
ValueError: invalid literal for int() with base 10: '[c19'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/user/Lector-dev/sorter.py", line 253, in pool_creator
    self.read_book, self.file_list)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: invalid literal for int() with base 10: '[c19'

Finished processing in 0.06375956535339355

**Comment by BasioMeusPuga** [comment]
Trivial fix for next commit.
