### ISSUE TITLE
Cannot Process books in library

### ISSUE THREAD

**Issue by wordlessly** [BasioMeusPuga/Lector#84]
1. library scan ignores PDFs
2. library scan detects epubs but 'cannot process' them.

See output below. Do I miss installing something?

9 books found
Cannot process: /home/nemo/Downloads/epub/one.epub
Cannot process: /home/nemo/Downloads/epub/two.epub
Cannot process: /home/nemo/Downloads/epub/three.epub
Cannot process: /home/nemo/Downloads/epub/four.epub
Cannot process: /home/nemo/Downloads/epub/five.epub
Cannot process: /home/nemo/Downloads/epub/six.epub
Cannot process: /home/nemo/Downloads/epub/seven.epub
Exception in thread Thread-36:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/nemo/Desktop/Lector/lector/sorter.py", line 195, in read_book
    book_ref.read_book()
  File "/home/nemo/Desktop/Lector/lector/parsers/pdf.py", line 41, in read_book
    self.metadata = BeautifulSoup(self.book.metadata(), 'xml')
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nemo/Desktop/Lector/lector/sorter.py", line 287, in pool_creator
    self.read_book, self.file_list)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?

Finished processing in 0.033007144927978516

**Comment by BasioMeusPuga** [comment]
You need the following packages installed. Please check your distro's package manager for whatever they might be called:

* python-poppler-qt5
* poppler-qt5
* python-lxml
