### ISSUE TITLE
Lector 0.5 does not start on ArchLinux

### ISSUE THREAD

**Issue by homocomputeris** [BasioMeusPuga/Lector#94]
After installing the AUR package, Lector has started once, but then
```
lector
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Locale: ru_RU (No translations found)
Traceback (most recent call last):
  File "/usr/bin/lector", line 11, in <module>
    load_entry_point('lector==0.5.0', 'gui_scripts', 'lector')()
  File "/usr/lib/python3.7/site-packages/lector/__main__.py", line 1074, in main
    form = MainUI()
  File "/usr/lib/python3.7/site-packages/lector/__main__.py", line 276, in __init__
    self.lib_ref.generate_model('build')
  File "/usr/lib/python3.7/site-packages/lector/library.py", line 104, in generate_model
    if position['is_read']:
KeyError: 'is_read'
```

**Comment by BasioMeusPuga** [comment]
I've corrected this. The fix should be in the AUR now.
