### ISSUE TITLE
can't start lector

### ISSUE THREAD

**Issue by dmitry-saritasa** [BasioMeusPuga/Lector#97]
Fedora 29

cloned latest master

```
commit 8fd6a0d432fa88b9e84b786baf7c04255a728d2d
```

when launch:

```
➜ python3 --version
Python 3.7.2

➜ lector
Traceback (most recent call last):
  File "/usr/local/bin/lector", line 11, in <module>
    load_entry_point('lector===0.5.GittyGittyBangBang', 'gui_scripts', 'lector')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/lector/__main__.py", line 42, in <module>
    from lector import sorter
  File "/usr/local/lib/python3.7/site-packages/lector/sorter.py", line 66, in <module>
    djvu_check = importlib.util.find_spec('djvu.decode')
  File "/usr/lib64/python3.7/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'djvu'
```

All dependencies listed in the doc installed

**Comment by BasioMeusPuga** [comment]
I've fixed this in the latest commit. For the record though, I don't think you have https://github.com/jwilk/python-djvulibre installed.
